
zipkin:
  storage:
    type: mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?characterEncoding=utf8&useSSL=true
    username: root
    password: wujiapeng123
    schema: classpath:/zipkin.sql
#    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9411